[package]
name = "blogd"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
actix-files = "0.6"
markdown = "1.0.0-alpha.11"
askama = "0.12.0"
actix-http = "3.3.1"
env_logger = "0.10.0"

